set -g default-terminal "screen-256color"

set -g status-bg "colour236"
set -g status-fg "colour253"

set -g status-left "#[fg=colour199]● #[fg=colour253]#S #[fg=colour240]|"
set -g status-right "#[fg=colour110]#(whoami) #[fg=colour240]| #[fg=colour45]%H:%M:%S #[fg=colour240]| #[fg=colour110]#(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-')"

setw -g window-status-current-format "#[fg=colour45]#I:#W#[fg=colour253]"
setw -g window-status-format "#[fg=colour253]#I:#W"
setw -g window-status-current-style "bold"
