set -g default-terminal "screen-256color"

set -g status-bg "colour235"
set -g status-fg "colour223"

set -g status-left "#[fg=colour208]● #[fg=colour223]#S #[fg=colour240]|"
set -g status-right "#[fg=colour142]#(whoami) #[fg=colour240]| #[fg=colour214]%H:%M:%S #[fg=colour240]| #[fg=colour142]#(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-')"

setw -g window-status-current-format "#[fg=colour214]#I:#W#[fg=colour223]"
setw -g window-status-format "#[fg=colour223]#I:#W"
setw -g window-status-current-style "bold"
