##### ===========================
#####        THEME LIGHT
##### ===========================

# True color
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

##### COLORS
set -g status-bg "colour255"
set -g status-fg "colour238"

##### STATUS BAR
set -g status-justify centre
set -g status-left-length 60
set -g status-right-length 120

##### LEFT SIDE
set -g status-left "#[fg=colour33]● #[fg=colour238]#S #[fg=colour240]|"

##### RIGHT SIDE
set -g status-right "#[fg=colour57]#(whoami) #[fg=colour240]| #[fg=colour33]%H:%M:%S #[fg=colour240]| #[fg=colour57]#(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-')"

##### WINDOW STYLE
setw -g window-status-current-format "#[fg=colour33]#I:#W#[fg=colour238]"
setw -g window-status-format "#[fg=colour238]#I:#W"
setw -g window-status-current-style "bold"
