set -g default-terminal "screen-256color"

set -g status-bg "colour237"
set -g status-fg "colour255"

set -g status-left "#[fg=colour81]● #[fg=colour255]#S #[fg=colour240]|"
set -g status-right "#[fg=colour109]#(whoami) #[fg=colour240]| #[fg=colour81]%H:%M:%S #[fg=colour240]| #[fg=colour109]#(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-')"

setw -g window-status-current-format "#[fg=colour81]#I:#W#[fg=colour255]"
setw -g window-status-format "#[fg=colour255]#I:#W"
setw -g window-status-current-style "bold"
