set -g default-terminal "screen-256color"

set -g status-bg "colour254"
set -g status-fg "colour136"

set -g status-left "#[fg=colour33]● #[fg=colour136]#S #[fg=colour240]|"
set -g status-right "#[fg=colour37]#(whoami) #[fg=colour240]| #[fg=colour33]%H:%M:%S #[fg=colour240]| #[fg=colour37]#(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-')"

setw -g window-status-current-format "#[fg=colour33]#I:#W#[fg=colour136]"
setw -g window-status-format "#[fg=colour136]#I:#W"
setw -g window-status-current-style "bold"
