# ============================
# Kitty Terminal Configuration 
# ============================

# Appearance
# ----------------------------

# Fonte e tamanho
#font_family      "FreeMono"
font_family      "FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
font_size        13.0

# Ligaduras (ótimo para programação)
enable_ligatures yes

# Cursor
cursor_shape     beam
cursor_blink     yes
cursor_animate   yes
cursor_beam_thickness 2

# Transparência
background_opacity 0.85
inactive_background_opacity 0.85

# Padding
window_padding_width 10
macos_fullscreen_padding_width 0

# Scrollback
scrollback_lines 10000
# -------- Tabs --------
# Se quiser usar tabs dentro do Kitty
enable_tab_bar yes
tab_bar_style powerline
active_tab_foreground #fdf6e3
active_tab_background #268bd2
inactive_tab_foreground #586e75
inactive_tab_background #073642

