# ============================
# Kitty Terminal Configuration
# ============================

# Editor
# ----------------------------

# Scroll com suavidade
scroll_on_output no
scrollback_lines 10000
enable_audio_bell no
visual_bell_duration 0.0
# Ativar ligaduras e renderização suave
experimental_features yes
