map ctrl+alt+h launch --location=hsplit
map ctrl+alt+v launch --location=vsplit
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+left previous_tab
map ctrl+shift+right next_tab
map ctrl+shift+f toggle_fullscreen
