# ============================
# Kitty Terminal Configuration
# ============================

include themes/default.conf
include settings/keymaps.conf
include settings/editor.conf
include settings/appearance.conf

